//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTodayProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInformation
    {
        public byte ID { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<byte> age { get; set; }
        public string nativePlace { get; set; }
        public string livingPlace { get; set; }
        public string relationStatus { get; set; }
        public string occupation { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string selfIntro { get; set; }
        public string phone { get; set; }
        public Nullable<int> salary { get; set; }
        public byte[] photo { get; set; }
    }
}
